version: "3.4"

services:
  php:
    image: matthiasnoback/symfony-decoupling-workshop-php
    build:
      context: .
      target: symfony_php
    volumes:
      - php_socket:/var/run/php
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./:/srv/app:rw,cached
      - var:/srv/app/var
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      APP_ENV: dev
    external_links:
      - "web:readapility.io"

  web:
    image: matthiasnoback/symfony-decoupling-workshop-web
    build:
      context: .
      target: symfony_nginx
    depends_on:
      - php
    volumes:
      - php_socket:/var/run/php
      - ./:/srv/app:rw,cached
    ports:
      # HTTP
      - target: 80
        published: 8080
        protocol: tcp

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - 1025
      - 1080:1080
###< symfony/mailer ###

volumes:
  php_socket:
  var:
