app_controllers:
    resource: ../src/Controller/
    type: annotation

tasks_controllers:
    resource: ../src/Tasks/Infrastructure/Http/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
